M48
; DRILL file {KiCad 8.0.6} date 2024-11-03T10:52:13+0100
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2024-11-03T10:52:13+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.6
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.500
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C1.800
%
G90
G05
T1
X107.66Y-41.465
X107.66Y-46.315
T2
X104.63Y-41.165
X104.63Y-46.615
M30
