M48
; DRILL file {KiCad 8.0.7} date 2025-04-18T20:19:53+0200
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-04-18T20:19:53+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.7
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.500
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C1.800
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C3.200
%
G90
G05
T1
X108.0Y-42.575
X108.0Y-47.425
T2
X104.97Y-42.275
X104.97Y-47.725
T3
X115.5Y-28.5
X115.5Y-79.0
X181.5Y-28.5
X181.5Y-79.0
M30
