M48
; DRILL file {KiCad 8.0.6} date 2024-12-01T22:22:07+0100
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2024-12-01T22:22:07+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.6
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.500
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C1.800
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C3.500
%
G90
G05
T1
X107.66Y-41.465
X107.66Y-46.315
T2
X104.63Y-41.165
X104.63Y-46.615
T3
X152.43Y-26.0
M30
